INSERT INTO provinces(id, code, name_kh, name_en)
VALUES
    (1, '1', 'ខេត្តបន្ទាយមានជ័យ', 'Banteay Meanchey Province'),
    (2, '2', 'ខេត្តបាត់ដំបង', 'Battambang Province'),
    (3, '3', 'ខេត្តកំពង់ចាម', 'Kampong Cham Province'),
    (4, '4', 'ខេត្តកំពង់ឆ្នាំង', 'Kampong Chhnang Province'),
    (5, '5', 'ខេត្តកំពង់ស្ពឺ', 'Kampong Speu Province'),
    (6, '6', 'ខេត្តកំពង់ធំ', 'Kampong Thom Province'),
    (7, '7', 'ខេត្តកំពត', 'Kampot Province'),
    (8, '8', 'ខេត្តកណ្ដាល', 'Kandal Province'),
    (9, '9', 'ខេត្តកោះកុង', 'Koh Kong Province'),
    (10, '10', 'ខេត្តក្រចេះ', 'Kratie Province'),
    (11, '11', 'ខេត្តមណ្ឌលគិរី', 'Mondul Kiri Province'),
    (12, '12', 'រាជធានីភ្នំពេញ', 'Phnom Penh Capital'),
    (13, '13', 'ខេត្តព្រះវិហារ', 'Preah Vihear Province'),
    (14, '14', 'ខេត្តព្រៃវែង', 'Prey Veng Province'),
    (15, '15', 'ខេត្តពោធិ៍សាត់', 'Pursat Province'),
    (16, '16', 'ខេត្តរតនគិរី', 'Ratanak Kiri Province'),
    (17, '17', 'ខេត្តសៀមរាប', 'Siemreap Province'),
    (18, '18', 'ខេត្តព្រះសីហនុ', 'Preah Sihanouk Province'),
    (19, '19', 'ខេត្តស្ទឹងត្រែង', 'Stung Treng Province'),
    (20, '20', 'ខេត្តស្វាយរៀង', 'Svay Rieng Province'),
    (21, '21', 'ខេត្តតាកែវ', 'Takeo Province'),
    (22, '22', 'ខេត្តឧត្ដរមានជ័យ', 'Oddar Meanchey Province'),
    (23, '23', 'ខេត្តកែប', 'Kep Province'),
    (24, '24', 'ខេត្តប៉ៃលិន', 'Pailin Province'),
    (25, '25', 'ខេត្តត្បូងឃ្មុំ', 'Tboung Khmum Province');
