export default [
    {
        title: "Dashboards",
        to: { name: "school-dashboards" },
        icon: { icon: "tabler-dashboard" },
        hideForRoles: ["teacher"],
    },
    {
        title: "Students",
        to: { name: "school-student-enroll" },
        icon: { icon: "tabler-users" },
        permission: "view-students",
    },
    {
        title: "Attendance",
        to: { name: "school-attendance" },
        icon: { icon: "tabler-file-check" },
        permission: "view-attendance",
    },
    {
        title: "Attendance Report",
        to: { name: "school-attendance-report" },
        icon: { icon: "tabler-report-analytics" },
        permission: "view-attendance",
    },
    {
        title: "Score Entry",
        to: { name: "school-score-entry" },
        icon: { icon: "tabler-file-check" },
        permission: "view-score-entry",
    },
    {
        title: "Schedule",
        to: { name: "school-schedule" },
        icon: { icon: "tabler-calendar" },
        permission: "view-schedules",
    },
    {
        title: "Classes",
        to: { name: "school-class" },
        icon: { icon: "tabler-home-cog" },
        permission: "view-classes",
        hideForRoles: ["teacher"],
    },
    {
        title: "Subjects",
        icon: { icon: "tabler-files" },
        to: { name: 'school-subject' },
        permission: "view-subjects",
    },
    {
        title: "Teachers",
        to: { name: "school-teacher" },
        icon: { icon: "tabler-user" },
        permission: "view-teachers",
    },
    {
        title: "Family",
        to: { name: "school-family" },
        icon: { icon: "tabler-users-group" },
        permission: "view-families",
    },
    {
        title: "Attendance & Score Entry",
        to: { name: "school-class-grid" },
        icon: { icon: "tabler-dashboard" },
        permission: "view-attendance-scoreentry",
    },
    {
        title: "Term Period",
        to: { name: "school-term-period" },
        icon: { icon: "tabler-calendar-time" },
        permission: "view-term-periods",
    },
];
