/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<
      'root',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '$error': RouteRecordInfo<
      '$error',
      '/:error(.*)',
      { error: ParamValue<true> },
      { error: ParamValue<false> },
      | never
    >,
    'account-types': RouteRecordInfo<
      'account-types',
      '/account-types',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-account-types': RouteRecordInfo<
      'admin-app-account-types',
      '/admin-app/account-types',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-activity-log': RouteRecordInfo<
      'admin-app-activity-log',
      '/admin-app/activity-log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-address-communes': RouteRecordInfo<
      'admin-app-address-communes',
      '/admin-app/address/communes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-address-districts': RouteRecordInfo<
      'admin-app-address-districts',
      '/admin-app/address/districts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-address-provinces': RouteRecordInfo<
      'admin-app-address-provinces',
      '/admin-app/address/provinces',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-address-villages': RouteRecordInfo<
      'admin-app-address-villages',
      '/admin-app/address/villages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-branches': RouteRecordInfo<
      'admin-app-branches',
      '/admin-app/branches',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-chart-accounts': RouteRecordInfo<
      'admin-app-chart-accounts',
      '/admin-app/chart-accounts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-close-entries': RouteRecordInfo<
      'admin-app-close-entries',
      '/admin-app/close-entries',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-close-entry-settings': RouteRecordInfo<
      'admin-app-close-entry-settings',
      '/admin-app/close-entry-settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-closed-days': RouteRecordInfo<
      'admin-app-closed-days',
      '/admin-app/closed-days',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-currencies': RouteRecordInfo<
      'admin-app-currencies',
      '/admin-app/currencies',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-dashboards': RouteRecordInfo<
      'admin-app-dashboards',
      '/admin-app/dashboards',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-departments': RouteRecordInfo<
      'admin-app-departments',
      '/admin-app/departments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-extract-image-text': RouteRecordInfo<
      'admin-app-extract-image-text',
      '/admin-app/extract-image-text',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-journal-settings': RouteRecordInfo<
      'admin-app-journal-settings',
      '/admin-app/journal-settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-loan-durations': RouteRecordInfo<
      'admin-app-loan-durations',
      '/admin-app/loan-durations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-loan-settings': RouteRecordInfo<
      'admin-app-loan-settings',
      '/admin-app/loan-settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-occupations': RouteRecordInfo<
      'admin-app-occupations',
      '/admin-app/occupations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-positions': RouteRecordInfo<
      'admin-app-positions',
      '/admin-app/positions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-roles': RouteRecordInfo<
      'admin-app-roles',
      '/admin-app/roles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-transfer-loans': RouteRecordInfo<
      'admin-app-transfer-loans',
      '/admin-app/transfer-loans',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-transfer-to-other-branch': RouteRecordInfo<
      'admin-app-transfer-to-other-branch',
      '/admin-app/transfer-to-other-branch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-transfer-under-user': RouteRecordInfo<
      'admin-app-transfer-under-user',
      '/admin-app/transfer-under-user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-users': RouteRecordInfo<
      'admin-app-users',
      '/admin-app/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-users-create': RouteRecordInfo<
      'admin-app-users-create',
      '/admin-app/users/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-app-users-edit': RouteRecordInfo<
      'admin-app-users-edit',
      '/admin-app/users/edit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'bad-debts': RouteRecordInfo<
      'bad-debts',
      '/bad-debts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'bad-debts-daily-list': RouteRecordInfo<
      'bad-debts-daily-list',
      '/bad-debts/daily-list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'bad-debts-result-list': RouteRecordInfo<
      'bad-debts-result-list',
      '/bad-debts/result-list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'cash-denominations': RouteRecordInfo<
      'cash-denominations',
      '/cash-denominations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'chart-accounts': RouteRecordInfo<
      'chart-accounts',
      '/chart-accounts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'clients-tab': RouteRecordInfo<
      'clients-tab',
      '/clients/:tab',
      { tab: ParamValue<true> },
      { tab: ParamValue<false> },
      | never
    >,
    'clients-client-profile': RouteRecordInfo<
      'clients-client-profile',
      '/clients/client-profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'close-entry-settings': RouteRecordInfo<
      'close-entry-settings',
      '/close-entry-settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboards': RouteRecordInfo<
      'dashboards',
      '/dashboards',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'deposit-transactions': RouteRecordInfo<
      'deposit-transactions',
      '/deposit-transactions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'deposit-transactions-withdraw-saving': RouteRecordInfo<
      'deposit-transactions-withdraw-saving',
      '/deposit-transactions/withdraw-saving',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'downloads-app-stores': RouteRecordInfo<
      'downloads-app-stores',
      '/downloads/app-stores',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'follow-up-loans': RouteRecordInfo<
      'follow-up-loans',
      '/follow-up-loans',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'human-resource-app': RouteRecordInfo<
      'human-resource-app',
      '/human-resource-app',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'human-resource-app-dashboards': RouteRecordInfo<
      'human-resource-app-dashboards',
      '/human-resource-app/dashboards',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'human-resource-app-employees': RouteRecordInfo<
      'human-resource-app-employees',
      '/human-resource-app/employees',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'human-resource-app-employees-create': RouteRecordInfo<
      'human-resource-app-employees-create',
      '/human-resource-app/employees/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'human-resource-app-employees-edit': RouteRecordInfo<
      'human-resource-app-employees-edit',
      '/human-resource-app/employees/edit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'human-resource-app-employees-profile': RouteRecordInfo<
      'human-resource-app-employees-profile',
      '/human-resource-app/employees/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'human-resource-app-job-reclassification': RouteRecordInfo<
      'human-resource-app-job-reclassification',
      '/human-resource-app/job-reclassification',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'human-resource-app-leaves': RouteRecordInfo<
      'human-resource-app-leaves',
      '/human-resource-app/leaves',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'human-resource-app-payrolls': RouteRecordInfo<
      'human-resource-app-payrolls',
      '/human-resource-app/payrolls',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'human-resource-app-pensions': RouteRecordInfo<
      'human-resource-app-pensions',
      '/human-resource-app/pensions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'human-resource-app-salaries': RouteRecordInfo<
      'human-resource-app-salaries',
      '/human-resource-app/salaries',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'human-resource-app-salaries-salary-details': RouteRecordInfo<
      'human-resource-app-salaries-salary-details',
      '/human-resource-app/salaries/salary-details',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'human-resource-app-sheet-attendances': RouteRecordInfo<
      'human-resource-app-sheet-attendances',
      '/human-resource-app/sheet-attendances',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'journal-classes': RouteRecordInfo<
      'journal-classes',
      '/journal-classes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'journal-settings': RouteRecordInfo<
      'journal-settings',
      '/journal-settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'journals-tab': RouteRecordInfo<
      'journals-tab',
      '/journals/:tab',
      { tab: ParamValue<true> },
      { tab: ParamValue<false> },
      | never
    >,
    'loans-tab': RouteRecordInfo<
      'loans-tab',
      '/loans/:tab',
      { tab: ParamValue<true> },
      { tab: ParamValue<false> },
      | never
    >,
    'loans-collects-collect-list': RouteRecordInfo<
      'loans-collects-collect-list',
      '/loans/collects/collect-list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'loans-collects-daily-collected-list': RouteRecordInfo<
      'loans-collects-daily-collected-list',
      '/loans/collects/daily-collected-list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'loans-loan-process-tab': RouteRecordInfo<
      'loans-loan-process-tab',
      '/loans/loan-process/:tab',
      { tab: ParamValue<true> },
      { tab: ParamValue<false> },
      | never
    >,
    'loans-reschedule': RouteRecordInfo<
      'loans-reschedule',
      '/loans/reschedule',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'loan-loans-restructure': RouteRecordInfo<
      'loan-loans-restructure',
      '/loans/restructure',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'loans-results-daily-results': RouteRecordInfo<
      'loans-results-daily-results',
      '/loans/results/daily-results',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'login': RouteRecordInfo<
      'login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'not-authorized': RouteRecordInfo<
      'not-authorized',
      '/not-authorized',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'other-journals-tab': RouteRecordInfo<
      'other-journals-tab',
      '/other-journals/:tab',
      { tab: ParamValue<true> },
      { tab: ParamValue<false> },
      | never
    >,
    'people': RouteRecordInfo<
      'people',
      '/people',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'performance': RouteRecordInfo<
      'performance',
      '/performance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports': RouteRecordInfo<
      'reports',
      '/reports',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-accounting-balance-sheet': RouteRecordInfo<
      'reports-accounting-balance-sheet',
      '/reports/accounting/balance-sheet',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-accounting-balance-sheet-daily': RouteRecordInfo<
      'reports-accounting-balance-sheet-daily',
      '/reports/accounting/balance-sheet/daily',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-accounting-balance-sheet-monthly': RouteRecordInfo<
      'reports-accounting-balance-sheet-monthly',
      '/reports/accounting/balance-sheet/monthly',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-accounting-balance-sheet-yearly': RouteRecordInfo<
      'reports-accounting-balance-sheet-yearly',
      '/reports/accounting/balance-sheet/yearly',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-accounting-branch-performance': RouteRecordInfo<
      'reports-accounting-branch-performance',
      '/reports/accounting/branch-performance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-accounting-cash-flow-summary': RouteRecordInfo<
      'reports-accounting-cash-flow-summary',
      '/reports/accounting/cash-flow-summary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-accounting-expense-summary': RouteRecordInfo<
      'reports-accounting-expense-summary',
      '/reports/accounting/expense-summary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-accounting-income-summary': RouteRecordInfo<
      'reports-accounting-income-summary',
      '/reports/accounting/income-summary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-accounting-profit-and-loss': RouteRecordInfo<
      'reports-accounting-profit-and-loss',
      '/reports/accounting/profit-and-loss',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-accounting-profit-and-loss-daily': RouteRecordInfo<
      'reports-accounting-profit-and-loss-daily',
      '/reports/accounting/profit-and-loss/daily',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-accounting-profit-and-loss-monthly': RouteRecordInfo<
      'reports-accounting-profit-and-loss-monthly',
      '/reports/accounting/profit-and-loss/monthly',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-accounting-profit-and-loss-yearly': RouteRecordInfo<
      'reports-accounting-profit-and-loss-yearly',
      '/reports/accounting/profit-and-loss/yearly',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-loan': RouteRecordInfo<
      'reports-loan',
      '/reports/loan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-loan-loan-disbursement': RouteRecordInfo<
      'reports-loan-loan-disbursement',
      '/reports/loan/loan-disbursement',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-loan-loan-operational': RouteRecordInfo<
      'reports-loan-loan-operational',
      '/reports/loan/loan-operational',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-loan-loan-portfolio': RouteRecordInfo<
      'reports-loan-loan-portfolio',
      '/reports/loan/loan-portfolio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-loan-loan-portfolio copy': RouteRecordInfo<
      'reports-loan-loan-portfolio copy',
      '/reports/loan/loan-portfolio copy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-loan-loan-repayment-status': RouteRecordInfo<
      'reports-loan-loan-repayment-status',
      '/reports/loan/loan-repayment-status',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-loan-loan-summary-repayment': RouteRecordInfo<
      'reports-loan-loan-summary-repayment',
      '/reports/loan/loan-summary-repayment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'schedules': RouteRecordInfo<
      'schedules',
      '/schedules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'second-page': RouteRecordInfo<
      'second-page',
      '/second-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'test': RouteRecordInfo<
      'test',
      '/test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'transaction-histories': RouteRecordInfo<
      'transaction-histories',
      '/transaction-histories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'user-profile-tab': RouteRecordInfo<
      'user-profile-tab',
      '/user-profile/:tab',
      { tab: ParamValue<true> },
      { tab: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
      | 'root'
      views:
      | never
    }
    'src/pages/[...error].vue': {
      routes:
      | '$error'
      views:
      | never
    }
    'src/pages/account-types/index.vue': {
      routes:
      | 'account-types'
      views:
      | never
    }
    'src/pages/admin-app/account-types/index.vue': {
      routes:
      | 'admin-app-account-types'
      views:
      | never
    }
    'src/pages/admin-app/activity-log/index.vue': {
      routes:
      | 'admin-app-activity-log'
      views:
      | never
    }
    'src/pages/admin-app/address/communes/index.vue': {
      routes:
      | 'admin-app-address-communes'
      views:
      | never
    }
    'src/pages/admin-app/address/districts/index.vue': {
      routes:
      | 'admin-app-address-districts'
      views:
      | never
    }
    'src/pages/admin-app/address/provinces/index.vue': {
      routes:
      | 'admin-app-address-provinces'
      views:
      | never
    }
    'src/pages/admin-app/address/villages/index.vue': {
      routes:
      | 'admin-app-address-villages'
      views:
      | never
    }
    'src/pages/admin-app/branches/index.vue': {
      routes:
      | 'admin-app-branches'
      views:
      | never
    }
    'src/pages/admin-app/chart-accounts/index.vue': {
      routes:
      | 'admin-app-chart-accounts'
      views:
      | never
    }
    'src/pages/admin-app/close-entries/index.vue': {
      routes:
      | 'admin-app-close-entries'
      views:
      | never
    }
    'src/pages/admin-app/close-entry-settings/index.vue': {
      routes:
      | 'admin-app-close-entry-settings'
      views:
      | never
    }
    'src/pages/admin-app/closed-days/index.vue': {
      routes:
      | 'admin-app-closed-days'
      views:
      | never
    }
    'src/pages/admin-app/currencies/index.vue': {
      routes:
      | 'admin-app-currencies'
      views:
      | never
    }
    'src/pages/admin-app/dashboards/index.vue': {
      routes:
      | 'admin-app-dashboards'
      views:
      | never
    }
    'src/pages/admin-app/departments/index.vue': {
      routes:
      | 'admin-app-departments'
      views:
      | never
    }
    'src/pages/admin-app/extract-image-text.vue': {
      routes:
      | 'admin-app-extract-image-text'
      views:
      | never
    }
    'src/pages/admin-app/journal-settings/index.vue': {
      routes:
      | 'admin-app-journal-settings'
      views:
      | never
    }
    'src/pages/admin-app/loan-durations/index.vue': {
      routes:
      | 'admin-app-loan-durations'
      views:
      | never
    }
    'src/pages/admin-app/loan-settings/index.vue': {
      routes:
      | 'admin-app-loan-settings'
      views:
      | never
    }
    'src/pages/admin-app/occupations/index.vue': {
      routes:
      | 'admin-app-occupations'
      views:
      | never
    }
    'src/pages/admin-app/positions/index.vue': {
      routes:
      | 'admin-app-positions'
      views:
      | never
    }
    'src/pages/admin-app/roles/index.vue': {
      routes:
      | 'admin-app-roles'
      views:
      | never
    }
    'src/pages/admin-app/transfer-loans/index.vue': {
      routes:
      | 'admin-app-transfer-loans'
      views:
      | never
    }
    'src/pages/admin-app/transfer-to-other-branch/index.vue': {
      routes:
      | 'admin-app-transfer-to-other-branch'
      views:
      | never
    }
    'src/pages/admin-app/transfer-under-user/index.vue': {
      routes:
      | 'admin-app-transfer-under-user'
      views:
      | never
    }
    'src/pages/admin-app/users/index.vue': {
      routes:
      | 'admin-app-users'
      views:
      | never
    }
    'src/pages/admin-app/users/create.vue': {
      routes:
      | 'admin-app-users-create'
      views:
      | never
    }
    'src/pages/admin-app/users/edit.vue': {
      routes:
      | 'admin-app-users-edit'
      views:
      | never
    }
    'src/pages/bad-debts/index.vue': {
      routes:
      | 'bad-debts'
      views:
      | never
    }
    'src/pages/bad-debts/daily-list.vue': {
      routes:
      | 'bad-debts-daily-list'
      views:
      | never
    }
    'src/pages/bad-debts/result-list.vue': {
      routes:
      | 'bad-debts-result-list'
      views:
      | never
    }
    'src/pages/cash-denominations/index.vue': {
      routes:
      | 'cash-denominations'
      views:
      | never
    }
    'src/pages/chart-accounts/index.vue': {
      routes:
      | 'chart-accounts'
      views:
      | never
    }
    'src/pages/clients/[tab].vue': {
      routes:
      | 'clients-tab'
      views:
      | never
    }
    'src/pages/clients/client-profile/index.vue': {
      routes:
      | 'clients-client-profile'
      views:
      | never
    }
    'src/pages/close-entry-settings/index.vue': {
      routes:
      | 'close-entry-settings'
      views:
      | never
    }
    'src/pages/dashboards/index.vue': {
      routes:
      | 'dashboards'
      views:
      | never
    }
    'src/pages/deposit-transactions/index.vue': {
      routes:
      | 'deposit-transactions'
      views:
      | never
    }
    'src/pages/deposit-transactions/withdraw-saving.vue': {
      routes:
      | 'deposit-transactions-withdraw-saving'
      views:
      | never
    }
    'src/pages/downloads/app-stores.vue': {
      routes:
      | 'downloads-app-stores'
      views:
      | never
    }
    'src/pages/follow-up-loans/index.vue': {
      routes:
      | 'follow-up-loans'
      views:
      | never
    }
    'src/pages/human-resource-app/index.vue': {
      routes:
      | 'human-resource-app'
      views:
      | never
    }
    'src/pages/human-resource-app/dashboards/index.vue': {
      routes:
      | 'human-resource-app-dashboards'
      views:
      | never
    }
    'src/pages/human-resource-app/employees/index.vue': {
      routes:
      | 'human-resource-app-employees'
      views:
      | never
    }
    'src/pages/human-resource-app/employees/create.vue': {
      routes:
      | 'human-resource-app-employees-create'
      views:
      | never
    }
    'src/pages/human-resource-app/employees/edit.vue': {
      routes:
      | 'human-resource-app-employees-edit'
      views:
      | never
    }
    'src/pages/human-resource-app/employees/profile/index.vue': {
      routes:
      | 'human-resource-app-employees-profile'
      views:
      | never
    }
    'src/pages/human-resource-app/job-reclassification/index.vue': {
      routes:
      | 'human-resource-app-job-reclassification'
      views:
      | never
    }
    'src/pages/human-resource-app/leaves/index.vue': {
      routes:
      | 'human-resource-app-leaves'
      views:
      | never
    }
    'src/pages/human-resource-app/payrolls/index.vue': {
      routes:
      | 'human-resource-app-payrolls'
      views:
      | never
    }
    'src/pages/human-resource-app/pensions/index.vue': {
      routes:
      | 'human-resource-app-pensions'
      views:
      | never
    }
    'src/pages/human-resource-app/salaries/index.vue': {
      routes:
      | 'human-resource-app-salaries'
      views:
      | never
    }
    'src/pages/human-resource-app/salaries/salary-details/index.vue': {
      routes:
      | 'human-resource-app-salaries-salary-details'
      views:
      | never
    }
    'src/pages/human-resource-app/sheet-attendances/index.vue': {
      routes:
      | 'human-resource-app-sheet-attendances'
      views:
      | never
    }
    'src/pages/journal-classes/index.vue': {
      routes:
      | 'journal-classes'
      views:
      | never
    }
    'src/pages/journal-settings/index.vue': {
      routes:
      | 'journal-settings'
      views:
      | never
    }
    'src/pages/journals/[tab].vue': {
      routes:
      | 'journals-tab'
      views:
      | never
    }
    'src/pages/loans/[tab].vue': {
      routes:
      | 'loans-tab'
      views:
      | never
    }
    'src/pages/loans/collects/collect-list.vue': {
      routes:
      | 'loans-collects-collect-list'
      views:
      | never
    }
    'src/pages/loans/collects/daily-collected-list.vue': {
      routes:
      | 'loans-collects-daily-collected-list'
      views:
      | never
    }
    'src/pages/loans/loan-process/[tab].vue': {
      routes:
      | 'loans-loan-process-tab'
      views:
      | never
    }
    'src/pages/loans/reschedule/index.vue': {
      routes:
      | 'loans-reschedule'
      views:
      | never
    }
    'src/pages/loans/restructure/index.vue': {
      routes:
      | 'loan-loans-restructure'
      views:
      | never
    }
    'src/pages/loans/results/daily-results.vue': {
      routes:
      | 'loans-results-daily-results'
      views:
      | never
    }
    'src/pages/login.vue': {
      routes:
      | 'login'
      views:
      | never
    }
    'src/pages/not-authorized.vue': {
      routes:
      | 'not-authorized'
      views:
      | never
    }
    'src/pages/other-journals/[tab].vue': {
      routes:
      | 'other-journals-tab'
      views:
      | never
    }
    'src/pages/people/index.vue': {
      routes:
      | 'people'
      views:
      | never
    }
    'src/pages/performance/index.vue': {
      routes:
      | 'performance'
      views:
      | never
    }
    'src/pages/reports/index.vue': {
      routes:
      | 'reports'
      views:
      | never
    }
    'src/pages/reports/accounting/balance-sheet/index.vue': {
      routes:
      | 'reports-accounting-balance-sheet'
      views:
      | never
    }
    'src/pages/reports/accounting/balance-sheet/daily.vue': {
      routes:
      | 'reports-accounting-balance-sheet-daily'
      views:
      | never
    }
    'src/pages/reports/accounting/balance-sheet/monthly.vue': {
      routes:
      | 'reports-accounting-balance-sheet-monthly'
      views:
      | never
    }
    'src/pages/reports/accounting/balance-sheet/yearly.vue': {
      routes:
      | 'reports-accounting-balance-sheet-yearly'
      views:
      | never
    }
    'src/pages/reports/accounting/branch-performance.vue': {
      routes:
      | 'reports-accounting-branch-performance'
      views:
      | never
    }
    'src/pages/reports/accounting/cash-flow-summary.vue': {
      routes:
      | 'reports-accounting-cash-flow-summary'
      views:
      | never
    }
    'src/pages/reports/accounting/expense-summary.vue': {
      routes:
      | 'reports-accounting-expense-summary'
      views:
      | never
    }
    'src/pages/reports/accounting/income-summary.vue': {
      routes:
      | 'reports-accounting-income-summary'
      views:
      | never
    }
    'src/pages/reports/accounting/profit-and-loss/index.vue': {
      routes:
      | 'reports-accounting-profit-and-loss'
      views:
      | never
    }
    'src/pages/reports/accounting/profit-and-loss/daily.vue': {
      routes:
      | 'reports-accounting-profit-and-loss-daily'
      views:
      | never
    }
    'src/pages/reports/accounting/profit-and-loss/monthly.vue': {
      routes:
      | 'reports-accounting-profit-and-loss-monthly'
      views:
      | never
    }
    'src/pages/reports/accounting/profit-and-loss/yearly.vue': {
      routes:
      | 'reports-accounting-profit-and-loss-yearly'
      views:
      | never
    }
    'src/pages/reports/loan/index.vue': {
      routes:
      | 'reports-loan'
      views:
      | never
    }
    'src/pages/reports/loan/loan-disbursement.vue': {
      routes:
      | 'reports-loan-loan-disbursement'
      views:
      | never
    }
    'src/pages/reports/loan/loan-operational.vue': {
      routes:
      | 'reports-loan-loan-operational'
      views:
      | never
    }
    'src/pages/reports/loan/loan-portfolio.vue': {
      routes:
      | 'reports-loan-loan-portfolio'
      views:
      | never
    }
    'src/pages/reports/loan/loan-portfolio copy.vue': {
      routes:
      | 'reports-loan-loan-portfolio copy'
      views:
      | never
    }
    'src/pages/reports/loan/loan-repayment-status.vue': {
      routes:
      | 'reports-loan-loan-repayment-status'
      views:
      | never
    }
    'src/pages/reports/loan/loan-summary-repayment.vue': {
      routes:
      | 'reports-loan-loan-summary-repayment'
      views:
      | never
    }
    'src/pages/schedules/index.vue': {
      routes:
      | 'schedules'
      views:
      | never
    }
    'src/pages/second-page.vue': {
      routes:
      | 'second-page'
      views:
      | never
    }
    'src/pages/test.vue': {
      routes:
      | 'test'
      views:
      | never
    }
    'src/pages/transaction-histories/index.vue': {
      routes:
      | 'transaction-histories'
      views:
      | never
    }
    'src/pages/user-profile/[tab].vue': {
      routes:
      | 'user-profile-tab'
      views:
      | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
    ? Info['routes']
    : keyof RouteNamedMap
}
