/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'accounting-dashboards': RouteRecordInfo<'accounting-dashboards', '/accounting/dashboards', Record<never, never>, Record<never, never>>,
    'accounting-user-profile-tab': RouteRecordInfo<'accounting-user-profile-tab', '/accounting/user-profile/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'admin-activity-log': RouteRecordInfo<'admin-activity-log', '/admin/activity-log', Record<never, never>, Record<never, never>>,
    'admin-address-communes': RouteRecordInfo<'admin-address-communes', '/admin/address/communes', Record<never, never>, Record<never, never>>,
    'admin-address-districts': RouteRecordInfo<'admin-address-districts', '/admin/address/districts', Record<never, never>, Record<never, never>>,
    'admin-address-provinces': RouteRecordInfo<'admin-address-provinces', '/admin/address/provinces', Record<never, never>, Record<never, never>>,
    'admin-address-villages': RouteRecordInfo<'admin-address-villages', '/admin/address/villages', Record<never, never>, Record<never, never>>,
    'admin-branches': RouteRecordInfo<'admin-branches', '/admin/branches', Record<never, never>, Record<never, never>>,
    'admin-curriculums': RouteRecordInfo<'admin-curriculums', '/admin/curriculums', Record<never, never>, Record<never, never>>,
    'admin-dashboards': RouteRecordInfo<'admin-dashboards', '/admin/dashboards', Record<never, never>, Record<never, never>>,
    'admin-positions': RouteRecordInfo<'admin-positions', '/admin/positions', Record<never, never>, Record<never, never>>,
    'admin-roles': RouteRecordInfo<'admin-roles', '/admin/roles', Record<never, never>, Record<never, never>>,
    'admin-students': RouteRecordInfo<'admin-students', '/admin/students', Record<never, never>, Record<never, never>>,
    'admin-students-create': RouteRecordInfo<'admin-students-create', '/admin/students/create', Record<never, never>, Record<never, never>>,
    'admin-students-edit-id': RouteRecordInfo<'admin-students-edit-id', '/admin/students/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-user-profile-tab': RouteRecordInfo<'admin-user-profile-tab', '/admin/user-profile/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'admin-users': RouteRecordInfo<'admin-users', '/admin/users', Record<never, never>, Record<never, never>>,
    'admin-users-create': RouteRecordInfo<'admin-users-create', '/admin/users/create', Record<never, never>, Record<never, never>>,
    'admin-users-edit': RouteRecordInfo<'admin-users-edit', '/admin/users/edit', Record<never, never>, Record<never, never>>,
    'admin-years': RouteRecordInfo<'admin-years', '/admin/years', Record<never, never>, Record<never, never>>,
    'dashboards': RouteRecordInfo<'dashboards', '/dashboards', Record<never, never>, Record<never, never>>,
    'hr-dashboards': RouteRecordInfo<'hr-dashboards', '/hr/dashboards', Record<never, never>, Record<never, never>>,
    'hr-user-profile-tab': RouteRecordInfo<'hr-user-profile-tab', '/hr/user-profile/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'loan-dashboards': RouteRecordInfo<'loan-dashboards', '/loan/dashboards', Record<never, never>, Record<never, never>>,
    'loan-user-profile-tab': RouteRecordInfo<'loan-user-profile-tab', '/loan/user-profile/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'scan': RouteRecordInfo<'scan', '/scan', Record<never, never>, Record<never, never>>,
    'school-class': RouteRecordInfo<'school-class', '/school/Class', Record<never, never>, Record<never, never>>,
    'school-class-detail-id': RouteRecordInfo<'school-class-detail-id', '/school/Class/detail/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'school-dashboards': RouteRecordInfo<'school-dashboards', '/school/dashboards', Record<never, never>, Record<never, never>>,
    'school-family': RouteRecordInfo<'school-family', '/school/family', Record<never, never>, Record<never, never>>,
    'school-family-detail-id': RouteRecordInfo<'school-family-detail-id', '/school/family/detail/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'school-grade': RouteRecordInfo<'school-grade', '/school/Grade', Record<never, never>, Record<never, never>>,
    'school-room': RouteRecordInfo<'school-room', '/school/Room', Record<never, never>, Record<never, never>>,
    'school-student-enroll': RouteRecordInfo<'school-student-enroll', '/school/StudentEnroll', Record<never, never>, Record<never, never>>,
    'school-subject': RouteRecordInfo<'school-subject', '/school/Subject', Record<never, never>, Record<never, never>>,
    'school-teacher': RouteRecordInfo<'school-teacher', '/school/Teacher', Record<never, never>, Record<never, never>>,
    'school-teacher-create': RouteRecordInfo<'school-teacher-create', '/school/Teacher/create', Record<never, never>, Record<never, never>>,
    'school-teacher-edit-id': RouteRecordInfo<'school-teacher-edit-id', '/school/Teacher/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'test': RouteRecordInfo<'test', '/test', Record<never, never>, Record<never, never>>,
  }
}
